### ISSUE TITLE
Does not work with PKG

### ISSUE THREAD

**Issue by TheDutchDev** [denyncrawford/native-barcode-scanner#1] opened 2021-06-14 13:26 UTC
This library doesn't seem to work with PKG(to build nodejs app as .exe).
Not entirely sure if it's this library, or the gkm library that seems to be used for communication with java.

https://www.npmjs.com/package/pkg

**Comment by denyncrawford** [comment] 2021-06-14 16:35
Hi DasNiels, I haven't tried it with pkg. Please can you give me the following info:
- Do you have Java installed? 
- What version do you have?
- Do you have a reproduction repo? 
- And have you tested without packaging?. 

Some time ago I had a problem with electron, packaging it as asar, I had to configure the the driver to not be packaged and this way it worked, I can imagine this is not your case because you need to pack the entire app, so let me do some tests and we'll see if there's a solution.

**Comment by TheDutchDev** [comment] 2021-06-14 17:14
Yes, I have java installed.
Latest version
Nope.
Yes, it works fine without pkg but as soon as its bundled it doesnt work anymore. No errors or whatsoever just nothing in the console

**Comment by denyncrawford** [comment] 2021-06-14 17:18
Well, I think the problem is related to [this line](https://github.com/tomzx/gkm/blob/b2d7bc986b4dbc8e5d5a6027760e10e21512df32/gkm.js#L10) on the gkm dependency. It spawns a binary that is located inside the module route, so it needs to be physically available on the desired route otherwise gkm.js can't execute the child process.

I don't know if there's a way to tell pkg to use the route or... even know if it transforms routes. Maybe it isn't packaging the thing right, so.. have to test.

**[EDIT]**: 

- Maybe this is related to [this issue](https://github.com/vercel/pkg/issues/671)
- As you can see [here](https://www.npmjs.com/package/pkg#detecting-assets-in-source-code) the files with path.join(__dirname, '../path/to/asset') should be automatically added as an asset, and assets are placed as raw data. So, maybe the gkm.jar binary is actually being loaded as an asset but the `JNativeHook.jar` binary that is required by this one isn't. This may be happening because it is not required by any js file, so a possible fix could be just adding it manually as an asset in the pkg config.

**Comment by TheDutchDev** [comment] 2021-06-15 17:17
Yeah I've tried adding those .jar files to assets. Also tried manually copy-pasting them over and whatnot. In the end nothing seems to work.

**Comment by denyncrawford** [comment] 2021-06-15 17:55
Can you tell me what version of node are you building for? I did tests and with node16 seems to work just fine, even if i don't define assets, you can check it on [this repo i just made](https://github.com/denyncrawford/nbs-test), also you can test building on your own, but there are built executables so you can check they work. Of course I made it with a keyboard simulator because I don't have the scanner here, but shouldn't be an issue. 

If you can provide me with more info about your project would be nice.
Please tell me if you have any progress.

**Comment by TheDutchDev** [comment] 2021-06-16 08:25
I'm using NodeJS v14.15.4. I've tried your example script on this node version and it results in the same as my own app. I've also installed nodejs v16 after this and tried your app again. Still the same results.

Not entirely sure if your app works at all tbh. I can't even get it to log the codes when running it as a node-app (npm run start).

**Comment by denyncrawford** [comment] 2021-06-16 12:16
**Well, I found the problem and made it work**!! Maybe I'll open an issue about it on pkg, but basically, what happens is that pkg creates something called a "snapshot" and it simulates a isolated filesystem, where java is not installed or even accessible over the PATH, and as I said, [this line](https://github.com/tomzx/gkm/blob/b2d7bc986b4dbc8e5d5a6027760e10e21512df32/gkm.js#L10) uses `path.join(__dirname, 'lib/gkm.jar')` wich is accessing the binary but it can't simply be executed by java.

The PKG docs indicates the only way possible to access the actual FS is with `process.cwd()` or `path.dirname(process.execPath)`. So a quick solution I fount is to replace that line I the gkm.js file with:

```JavaScript
const route = path.join(process.cwd(), 'node_modules/gkm')
var gkm = spawn('java', ['-jar', path.join(route, 'lib/gkm.jar')]);
```

You can tell this is not the best way to do it because it means that no matter how do you want to distribute your app, it needs gkm to be available, and worst, the script must run from CWD which means that you would need to calculate your execution path everytime you want to run the app. Even if you take out the binaries to the root folder of your app to distribute them with it, what if user executes the script from another CWD?.

So, I don't know if there's a way to making Java accessible from the snapshot or at least to install it. **If you want to test, you can pull the test repo and replace the lines in the example above**.

I will let this open until your confirmation.

**Comment by denyncrawford** [comment] 2021-06-17 01:11
### New deno port available:

If you can use deno in your project I just made a module for deno and it works perfect, if you want to test just create a js or ts file with this:

```typescript
//index.ts
import BarcodeScanner from "https://deno.land/x/barcode_scanner@1.0.1/mod.ts";

const scanner = new BarcodeScanner({
  endKeys: 'Intro'
});

scanner.on('code', (code:string) => {
  console.log(code);
});
```
**If you want to compile run**:

```bash
deno compile -A --unstable index.ts
```

**It will work on avery machine** that has Java installed as an executable, you don't need to install any binary, it does it automatically on your `home/gkm` directory and you can remove them any time.

If you want to chek the repo: [barcode-scanner](https://github.com/denyncrawford/barcode-scanner), the API is almost the same, so won't be an issue, greetings mate.

**Comment by TheDutchDev** [comment] 2021-06-17 08:16
Oh, never heard of deno. not even when I was googling "nodejs compile to executable" or stuff like that. It looks very promising though. I'll have a go at it and let you know ASAP.

I really appreciate the effort you've put into this by the way. Doesn't happen very often when creating issues :P

**Comment by TheDutchDev** [comment] 2021-06-17 08:24
UPDATE: The deno version works! Thanks alot mate. I'm gonna stick to the deno version.

One thing I'm wondering though is, what did you change to make it work in deno? Does it still use java, or does deno just compile it differently?

**Comment by denyncrawford** [comment] 2021-06-17 10:40
Great, dude! I think I did not explain myself with the java thing, it does need java still, and it uses deno GKM which is the binary that allows to listen the input events, my gkm module automatically downloads it for you. 

Also, there's no difference between the no compiled code and the built one on fact if you just run `deno run -A --unstable index.ts`, it will be the same as in the example above. Deno compile gives you access to the os stuff and that's why it can use java but will run on every machine without deno installed. 

In the future I have plans to download a JRE binary if there's no java in the system already, or even make it optional in the module configuration. Anyway, I'm also looking for a rust solution, since it wouldn't need any dependency as java, so it is 100% ready to go.

Awesome to hear it worked for you, greetings mate. I'm closing this issue.

**Closed as completed** 2021-06-17 11:44 UTC
Labels: needs-investigation
